name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Cache
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install and Build
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build # will run `yarn build` command
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: export # will run `yarn export` command
        run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
