name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Cache  💾
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**yarn.lock') }}

      - name: Setup Node 🔧
        uses: actions/setup-node@v1

      - run: npm install

      - run: npm run deploy

      - run: mkdir out/assets

      - run: mv out/_next/* out/assets

      - run: rm -rf out/next/

      - run: find . -type f -exec sed -i -e 's/\/_next//' {} \;

      - run: touch out/.nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          ACCESS_TOKEN: ${{secrets.DEPLOY_KEY}}
          BRANCH: gh-pages
          FOLDER: out
          CLEAN: true
