name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      - name: Cache  💾
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install and Build 🔧
        uses: actions/setup-node@v1
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install # will run `yarn install` command
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: deploy # will run `yarn install` command

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          BRANCH: gh-pages 
          FOLDER: build 
          CLEAN: true 
